from __future__ import annotations

import csv
import sqlite3
import sys
from pathlib import Path

from pypdf import PdfReader

import app


APP_DIR = Path(__file__).resolve().parent
PDF_PATH = Path(r"C:\Users\BJ\Desktop\jinlingkejixueyuanshiyanshianquanshoucenew.pdf")
CSV_PATH = APP_DIR / "jinling_lab_safety_manual_questions.csv"
TEXT_PATH = APP_DIR / "jinling_lab_safety_manual_extracted.txt"
SOURCE = "pdf_manual_jinling_2024"


QUESTIONS = [
    {
        "question_type": "single",
        "question": "事故发生时，处置优先次序中第一位是什么？",
        "option_a": "保护人身安全",
        "option_b": "保存学术资料",
        "option_c": "清理现场痕迹",
        "option_d": "先恢复实验进度",
        "answer": "A",
        "explanation": "手册应急指南要求事故发生时首先保护人身安全，其次保护公众财产安全，再保存学术资料。",
    },
    {
        "question_type": "multi",
        "question": "电话求助时，应告知哪些信息？",
        "option_a": "事故地点",
        "option_b": "事故性质和严重程度",
        "option_c": "求助者姓名、所处位置、联系电话",
        "option_d": "与事故无关的个人爱好",
        "answer": "ABC",
        "explanation": "手册应急指南列明电话求助应说明事故地点、性质和严重程度，以及求助者姓名、位置和联系电话。",
    },
    {
        "question_type": "single",
        "question": "实验室发生火灾时，常用火警电话是？",
        "option_a": "110",
        "option_b": "119",
        "option_c": "120",
        "option_d": "122",
        "answer": "B",
        "explanation": "手册常用电话中列明火警电话为 119。",
    },
    {
        "question_type": "single",
        "question": "实验室发生医疗急救需求时，常用急救电话是？",
        "option_a": "110",
        "option_b": "119",
        "option_c": "120",
        "option_d": "114",
        "answer": "C",
        "explanation": "手册常用电话中列明医疗急救为 120。",
    },
    {
        "question_type": "single",
        "question": "进入实验室前，未经过相关安全教育并取得合格成绩的人员应如何处理？",
        "option_a": "不得进入实验室",
        "option_b": "可以在同学陪同下进入",
        "option_c": "只要不动设备就可以进入",
        "option_d": "填写承诺书即可进入",
        "answer": "A",
        "explanation": "一般安全守则规定，未经相关安全教育并取得合格成绩的人员不得进入实验室。",
    },
    {
        "question_type": "multi",
        "question": "实验人员应熟悉实验室环境中的哪些内容？",
        "option_a": "水、电、气阀门位置",
        "option_b": "安全通道位置",
        "option_c": "灭火和应急设备位置及使用方法",
        "option_d": "无关人员的私人信息",
        "answer": "ABC",
        "explanation": "手册要求实验人员熟悉水电气阀门、安全通道、急救电话、灭火和应急设备的位置与使用方法。",
    },
    {
        "question_type": "single",
        "question": "实验室内下列哪项行为是禁止的？",
        "option_a": "佩戴必要个人防护用品",
        "option_b": "保持消防通道通畅",
        "option_c": "吸烟、饮食或睡觉",
        "option_d": "实验结束后关闭水电气",
        "answer": "C",
        "explanation": "手册明确实验室内禁止吸烟、饮食、睡觉、使用明火电器。",
    },
    {
        "question_type": "judge",
        "question": "实验室内禁止吸烟、饮食和睡觉。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册一般安全守则明确实验室内禁止吸烟、饮食、睡觉、使用明火电器。",
    },
    {
        "question_type": "judge",
        "question": "严禁穿露趾鞋、短裤进入实验室。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "一般安全守则明确严禁穿露趾鞋、短裤进入实验室。",
    },
    {
        "question_type": "judge",
        "question": "开展危险实验时，可以由一名学生独自进行。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "F",
        "explanation": "手册要求进行危险实验时至少 2 人在场，不得擅自离岗。",
    },
    {
        "question_type": "single",
        "question": "实验结束后，最后一个离开实验室的人员必须检查并关闭什么？",
        "option_a": "整个实验室的水、电、气、门窗",
        "option_b": "只需关闭电脑显示器",
        "option_c": "只需带走个人物品",
        "option_d": "只需关闭空调",
        "answer": "A",
        "explanation": "一般安全守则要求最后离开者检查并关闭整个实验室的水、电、气、门窗。",
    },
    {
        "question_type": "multi",
        "question": "发生火灾、爆炸、危险品被盗或泄漏等安全事故时，应采取哪些措施？",
        "option_a": "启动事故应急处理方案",
        "option_b": "采取有效应急措施",
        "option_c": "向学校主管部门、保卫处报告，必要时向相关行政主管部门报告",
        "option_d": "隐瞒事故以免影响实验进度",
        "answer": "ABC",
        "explanation": "手册要求立即根据情况启动应急方案，采取措施并报告，事故经过和处理情况应记录存档。",
    },
    {
        "question_type": "multi",
        "question": "实验室火灾隐患通常包括哪些？",
        "option_a": "电器设备过载、线路老化或短路",
        "option_b": "易燃易爆、有毒有害化学品存放与使用不规范",
        "option_c": "消防通道不畅、废旧物品未及时清理",
        "option_d": "消防通道保持畅通",
        "answer": "ABC",
        "explanation": "消防安全章节列举了电器过载、化学品管理不规范、消防通道不畅等火灾隐患。",
    },
    {
        "question_type": "single",
        "question": "实验室消防器材应放置在哪里？",
        "option_a": "便于取用的明显位置",
        "option_b": "锁在无人知道的柜子里",
        "option_c": "堆放在杂物后面",
        "option_d": "只放在楼外",
        "answer": "A",
        "explanation": "手册要求消防器材放在便于取用的明显位置，指定专人管理并定期检查更换。",
    },
    {
        "question_type": "judge",
        "question": "使用和储存易燃、易爆物品的实验室必须严禁烟火。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "防火防爆须知明确使用和储存易燃、易爆物品的实验室必须严禁烟火。",
    },
    {
        "question_type": "single",
        "question": "实验室中严禁用什么替代保险丝？",
        "option_a": "金属丝",
        "option_b": "合格熔丝",
        "option_c": "空气开关",
        "option_d": "漏电保护器",
        "answer": "A",
        "explanation": "手册防火防爆须知要求不得乱接乱拉电线，严禁用金属丝代替保险丝。",
    },
    {
        "question_type": "judge",
        "question": "电加热器、电烤箱等设备应做到人走电断。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册要求电加热器、电烤箱等设备做到人走电断。",
    },
    {
        "question_type": "single",
        "question": "氢、氧和乙炔不能混放一处，并应与使用火源保持多远以上距离？",
        "option_a": "1 米",
        "option_b": "3 米",
        "option_c": "10 米",
        "option_d": "30 米",
        "answer": "C",
        "explanation": "手册规定氢、氧和乙炔不能混放一处，要与使用的火源保持 10 米以上距离。",
    },
    {
        "question_type": "multi",
        "question": "火灾处理原则中的“四会”包括哪些？",
        "option_a": "会报警",
        "option_b": "会使用灭火器",
        "option_c": "会灭初期火、会逃生",
        "option_d": "会隐瞒火情",
        "answer": "ABC",
        "explanation": "手册列明“四会”为会报警、会使用灭火器、会灭初期火、会逃生。",
    },
    {
        "question_type": "single",
        "question": "报警时，下列哪项做法是正确的？",
        "option_a": "陈述火灾发生详细地址和起火物质、火势等情况",
        "option_b": "只说“着火了”就挂断",
        "option_c": "不报姓名和联系电话",
        "option_d": "等对方询问前先挂断",
        "answer": "A",
        "explanation": "手册要求报警时说明详细地址、原因、起火物质与火势，并报姓名、位置和电话，切勿先挂断。",
    },
    {
        "question_type": "single",
        "question": "火灾逃生时，下列哪项是禁止的？",
        "option_a": "通过电梯逃生",
        "option_b": "用湿毛巾遮鼻",
        "option_c": "匍匐撤离",
        "option_d": "保持冷静按路线撤离",
        "answer": "A",
        "explanation": "火灾逃生章节明确禁止通过电梯逃生。",
    },
    {
        "question_type": "single",
        "question": "身上着火时，正确做法是？",
        "option_a": "快速奔跑让火熄灭",
        "option_b": "迅速脱去衣服，或用水、就地打滚、覆盖厚重衣服灭火",
        "option_c": "继续实验",
        "option_d": "用手拍打火焰即可",
        "answer": "B",
        "explanation": "手册指出身上着火应迅速脱衣或用水、就地打滚、覆盖厚重衣服等方式灭火，切不可奔跑。",
    },
    {
        "question_type": "judge",
        "question": "大功率实验设备用电应使用专线，防止超负荷用电着火。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "水电安全章节要求大功率实验设备用电应使用专线，谨防超负荷用电着火。",
    },
    {
        "question_type": "single",
        "question": "发生电气火灾时，首先应做什么？",
        "option_a": "切断电源，尽快拉闸断电",
        "option_b": "立即用水扑救",
        "option_c": "继续使用设备",
        "option_d": "打开所有电器开关",
        "answer": "A",
        "explanation": "手册要求发生电气火灾时首先切断电源，拉闸断电后再灭火。",
    },
    {
        "question_type": "multi",
        "question": "扑灭电气火灾时，可使用哪些灭火剂？",
        "option_a": "干粉灭火器",
        "option_b": "二氧化碳灭火器",
        "option_c": "干燥砂子",
        "option_d": "水或泡沫灭火器",
        "answer": "ABC",
        "explanation": "手册要求用绝缘性能好的灭火剂，如干粉、二氧化碳或干燥砂子，严禁用导电灭火剂。",
    },
    {
        "question_type": "judge",
        "question": "严禁手上有水或潮湿时接触电器设备。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "安全用电须知明确严禁手上有水或潮湿接触电器设备。",
    },
    {
        "question_type": "single",
        "question": "触电救援中，若无法及时断开电源，应如何使触电者脱离电源？",
        "option_a": "直接用手拉开触电者",
        "option_b": "用干燥木棒、竹竿等绝缘物挑开电线",
        "option_c": "用湿毛巾拉开电线",
        "option_d": "继续等待",
        "answer": "B",
        "explanation": "手册要求无法断电时用干燥木棒、竹竿等绝缘物挑开电线，不得直接触碰。",
    },
    {
        "question_type": "single",
        "question": "成人心肺复苏胸外按压的频率通常为？",
        "option_a": "30-40 次/分",
        "option_b": "60-80 次/分",
        "option_c": "100-120 次/分",
        "option_d": "180-200 次/分",
        "answer": "C",
        "explanation": "手册触电急救部分列明胸外按压频率为 100-120 次/分。",
    },
    {
        "question_type": "single",
        "question": "实验室发生漏水和浸水时，应第一时间做什么？",
        "option_a": "关闭水阀",
        "option_b": "打开更多水龙头",
        "option_c": "继续实验",
        "option_d": "只拍照不处理",
        "answer": "A",
        "explanation": "用水安全章节要求实验室发生漏水和浸水时第一时间关闭水阀。",
    },
    {
        "question_type": "single",
        "question": "危险化学品的性质通常不包括下列哪项？",
        "option_a": "毒害",
        "option_b": "腐蚀",
        "option_c": "爆炸、燃烧或助燃",
        "option_d": "绝对无害",
        "answer": "D",
        "explanation": "手册引用条例说明危险化学品具有毒害、腐蚀、爆炸、燃烧、助燃等危害性质。",
    },
    {
        "question_type": "single",
        "question": "危险货物分类中，第二类是？",
        "option_a": "爆炸品",
        "option_b": "气体",
        "option_c": "易燃液体",
        "option_d": "腐蚀性物质",
        "answer": "B",
        "explanation": "手册化学品分类中第二类为气体。",
    },
    {
        "question_type": "single",
        "question": "危险货物分类中，第八类是？",
        "option_a": "腐蚀性物质",
        "option_b": "放射性物质",
        "option_c": "易燃液体",
        "option_d": "气体",
        "answer": "A",
        "explanation": "手册列明第八类为腐蚀性物质，如盐酸、硫酸、硝酸等。",
    },
    {
        "question_type": "multi",
        "question": "一般化学品保存场所应具备哪些条件？",
        "option_a": "整洁、通风、隔热、安全",
        "option_b": "远离热源、火源、电源和水源",
        "option_c": "避免阳光直射",
        "option_d": "与食品混放",
        "answer": "ABC",
        "explanation": "手册要求存放化学品的场所整洁、通风、隔热、安全，远离热源火源电源水源并避免阳光直射。",
    },
    {
        "question_type": "judge",
        "question": "实验室不得存放大桶试剂和大量试剂，禁止把实验室当作仓库使用。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "化学品保存原则明确禁止把实验室当作仓库使用。",
    },
    {
        "question_type": "single",
        "question": "化学品容器和配制试剂应具备什么要求？",
        "option_a": "贴有明显标签",
        "option_b": "标签越少越好",
        "option_c": "只靠颜色区分",
        "option_d": "无标签也可盲目使用",
        "answer": "A",
        "explanation": "手册要求所有化学品和配制试剂都应贴有明显标签。",
    },
    {
        "question_type": "multi",
        "question": "配制试剂、反应产物等标签通常应包含哪些信息？",
        "option_a": "名称",
        "option_b": "浓度或纯度",
        "option_c": "责任人、日期",
        "option_d": "无关装饰图案",
        "answer": "ABC",
        "explanation": "手册要求配制试剂、反应产物等标贴名称、浓度或纯度、责任人、日期等信息。",
    },
    {
        "question_type": "single",
        "question": "剧毒化学品执行的“五双”管理不包括下列哪项？",
        "option_a": "双人验收",
        "option_b": "双人保管",
        "option_c": "双把锁、双本账",
        "option_d": "单人随意领取",
        "answer": "D",
        "explanation": "手册列明剧毒化学品执行双人验收、双人保管、双人发货、双把锁、双本账。",
    },
    {
        "question_type": "single",
        "question": "腐蚀品较适宜放置在哪里？",
        "option_a": "防腐蚀试剂柜下层或下垫防腐蚀托盘",
        "option_b": "高处开放架最上层",
        "option_c": "食品冰箱中",
        "option_d": "消防通道上",
        "answer": "A",
        "explanation": "手册危险品分类存放要求腐蚀品放在防腐蚀试剂柜下层或下垫防腐蚀托盘。",
    },
    {
        "question_type": "judge",
        "question": "不相容、相互作用会发生剧烈反应的化学品不得混放。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "化学品保存原则明确不得将不相容、会剧烈反应的化学品混放。",
    },
    {
        "question_type": "single",
        "question": "化学品使用前，操作者应了解什么？",
        "option_a": "化学品安全技术说明书 SDS/MSDS",
        "option_b": "无关网页评价",
        "option_c": "只看瓶子颜色",
        "option_d": "只凭气味判断",
        "answer": "A",
        "explanation": "化学品安全管理要求使用前了解化学品性质和安全信息，SDS/MSDS 是重要依据。",
    },
    {
        "question_type": "single",
        "question": "处理化学废弃物的基本原则是？",
        "option_a": "分类收集、规范处置",
        "option_b": "所有废液直接倒入水槽",
        "option_c": "酸碱与有机废液任意混合",
        "option_d": "挥发掉即可",
        "answer": "A",
        "explanation": "手册化学品安全章节要求废弃物规范处置，避免混合不相容废弃物。",
    },
    {
        "question_type": "single",
        "question": "病原微生物按照传染性和危害程度分为几类？",
        "option_a": "两类",
        "option_b": "三类",
        "option_c": "四类",
        "option_d": "九类",
        "answer": "C",
        "explanation": "生物安全章节按传染性和危害程度将病原微生物分为四类。",
    },
    {
        "question_type": "judge",
        "question": "涉及病原微生物的实验活动应按照相应生物安全等级和规程进行。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "生物安全章节要求按照生物安全等级和实验室规程开展相关活动。",
    },
    {
        "question_type": "single",
        "question": "生物安全废弃物通常应如何处理？",
        "option_a": "按规定分类收集、消毒灭菌或交由有资质单位处理",
        "option_b": "混入普通生活垃圾",
        "option_c": "带回宿舍处理",
        "option_d": "随意倒入水槽",
        "answer": "A",
        "explanation": "生物安全章节强调废弃物应按要求分类、消毒灭菌和规范处置。",
    },
    {
        "question_type": "single",
        "question": "辐射防护的基本原则不包括下列哪项？",
        "option_a": "缩短受照时间",
        "option_b": "增大与辐射源距离",
        "option_c": "采取屏蔽防护",
        "option_d": "尽量长时间近距离接触辐射源",
        "answer": "D",
        "explanation": "辐射防护通常遵循时间、距离、屏蔽三原则；长时间近距离接触会增加风险。",
    },
    {
        "question_type": "judge",
        "question": "短半衰期核素固液废弃物放置 10 个半衰期，经检测达标后可作为普通废物处理。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册辐射废弃物处置部分列明短半衰期核素固液废弃物放置 10 个半衰期并检测达标后处理。",
    },
    {
        "question_type": "single",
        "question": "从事激光操作的人员应满足什么要求？",
        "option_a": "经过专业培训，培训合格后上岗",
        "option_b": "任何人都可直接操作",
        "option_c": "只需戴普通眼镜",
        "option_d": "无需检查和培训",
        "answer": "A",
        "explanation": "激光安全章节要求从事激光操作的人员须经过专业培训，合格后上岗。",
    },
    {
        "question_type": "judge",
        "question": "即使佩戴防护镜，也不能直视激光束。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册激光安全章节明确即使佩戴防护镜也不能直视激光束。",
    },
    {
        "question_type": "single",
        "question": "使用激光前，个人防护中应摘掉哪类物品？",
        "option_a": "手表等可以反光的配饰",
        "option_b": "防护眼镜",
        "option_c": "防燃工作服",
        "option_d": "安全标识",
        "answer": "A",
        "explanation": "激光安全章节要求使用激光前摘掉手表等可反光配饰，并穿戴合适防护用品。",
    },
    {
        "question_type": "single",
        "question": "压力设备启用长期停用的压力容器前，应如何处理？",
        "option_a": "经特种设备管理部门检验合格后使用",
        "option_b": "直接满负荷使用",
        "option_c": "只擦拭外表即可",
        "option_d": "由未培训人员试用",
        "answer": "A",
        "explanation": "特种设备安全章节要求启用长期停用的压力容器须经检验合格后才能使用。",
    },
    {
        "question_type": "judge",
        "question": "压力设备从业人员须经过培训，持证上岗，并严格按照规程操作。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册压力设备安全要求从业人员培训、持证上岗并按规程操作。",
    },
    {
        "question_type": "single",
        "question": "起重机械不得起吊什么物体？",
        "option_a": "超过额定载重量的物体",
        "option_b": "额定范围内的物体",
        "option_c": "已检查合格的物体",
        "option_d": "按规程捆扎的物体",
        "answer": "A",
        "explanation": "手册起重机械安全要求不得起吊超过额定载重量的物体。",
    },
    {
        "question_type": "judge",
        "question": "无论任何情况下，起重机械操控范围内严禁站人。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "起重机械安全章节明确操控范围内严禁站人。",
    },
    {
        "question_type": "multi",
        "question": "气体钢瓶存放地应满足哪些要求？",
        "option_a": "严禁明火",
        "option_b": "保持通风和干燥",
        "option_c": "避免阳光直射",
        "option_d": "可存放在走廊和公共场所",
        "answer": "ABC",
        "explanation": "手册要求气体钢瓶存放地严禁明火，保持通风干燥、避免阳光直射，不得存放在走廊和公共场所。",
    },
    {
        "question_type": "single",
        "question": "气体钢瓶应如何放置？",
        "option_a": "直立放置并妥善固定",
        "option_b": "横放在地上滚动取用",
        "option_c": "倒置悬挂",
        "option_d": "不用固定",
        "answer": "A",
        "explanation": "手册要求气体钢瓶直立放置并妥善固定，防止跌倒。",
    },
    {
        "question_type": "single",
        "question": "开启气体钢瓶时的正确顺序是？",
        "option_a": "先开总阀，后开减压阀",
        "option_b": "先开减压阀，后开总阀",
        "option_c": "只开减压阀",
        "option_d": "同时猛开所有阀门",
        "answer": "A",
        "explanation": "手册规定开启钢瓶时先开总阀，后开减压阀。",
    },
    {
        "question_type": "single",
        "question": "关闭气体钢瓶时的正确顺序是？",
        "option_a": "先关总阀，放尽余气后再关减压阀",
        "option_b": "只关减压阀不关总阀",
        "option_c": "先拆管路再关阀",
        "option_d": "无需关闭",
        "answer": "A",
        "explanation": "手册规定关闭钢瓶时先关总阀，放尽余气后，再关减压阀。",
    },
    {
        "question_type": "single",
        "question": "发现气体泄漏时，下列哪项措施是错误的？",
        "option_a": "关闭气源",
        "option_b": "开窗通风、疏散人员",
        "option_c": "在易燃易爆气体泄漏时开关电源",
        "option_d": "采取应急措施",
        "answer": "C",
        "explanation": "手册要求发现泄漏应关闭气源、通风、疏散；易燃易爆气体泄漏时切忌开关电源。",
    },
    {
        "question_type": "single",
        "question": "机械加工设备操作时，下列哪项不符合安全要求？",
        "option_a": "佩戴必要防护器具",
        "option_b": "束缚好宽松衣物和头发",
        "option_c": "佩戴长项链、长丝巾和领带",
        "option_d": "严格遵守操作规程",
        "answer": "C",
        "explanation": "手册要求不得佩戴长项链、长丝巾和领带等易被卷入或缠绕的物品。",
    },
    {
        "question_type": "judge",
        "question": "食品、饮料严禁存放在实验室冰箱内。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "冰箱安全章节明确食品、饮料严禁存放在实验室冰箱内。",
    },
    {
        "question_type": "single",
        "question": "存放危险化学药品的冰箱应采取什么措施？",
        "option_a": "粘贴警示标识，药品粘贴标签并定期清理",
        "option_b": "不贴任何标签",
        "option_c": "与食品饮料混放",
        "option_d": "放在热源旁边",
        "answer": "A",
        "explanation": "手册要求存放危险化学药品的冰箱粘贴警示标识，冰箱内药品贴标签并定期清理。",
    },
    {
        "question_type": "single",
        "question": "高速离心机启动前应注意什么？",
        "option_a": "扣紧盖子，选择合适转子和离心管并确保平衡",
        "option_b": "打开盖子观察",
        "option_c": "使用有裂纹离心管",
        "option_d": "不需要配平",
        "answer": "A",
        "explanation": "高速离心机安全要求启动前扣紧盖子，选择合适转子和离心管，安放均匀确保平衡。",
    },
    {
        "question_type": "judge",
        "question": "不能在未切断电源时打开离心机盖子。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "高速离心机安全要求确保分离开关正常，不能在未切断电源时打开盖子。",
    },
    {
        "question_type": "single",
        "question": "使用加热设备时，下列哪项是正确的？",
        "option_a": "人员不得离岗，使用完毕立即断开电源",
        "option_b": "周围堆放易燃易爆物",
        "option_c": "用电热设备烘烤溶剂、油品",
        "option_d": "使用完毕无需断电",
        "answer": "A",
        "explanation": "加热设备安全要求使用时人员不得离岗，使用完毕应立即断开电源。",
    },
    {
        "question_type": "judge",
        "question": "实验室一般不允许使用明火电炉，特殊情况需申请明火电炉使用许可证。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册规定实验室不允许使用明火电炉，特殊情况确需使用须申请许可证。",
    },
    {
        "question_type": "single",
        "question": "通风柜内进行操作时，较合适的位置是距离通风柜内至少多少厘米？",
        "option_a": "5 cm",
        "option_b": "10 cm",
        "option_c": "15 cm",
        "option_d": "50 cm",
        "answer": "C",
        "explanation": "手册要求应在距离通风柜内至少 15cm 的地方进行操作。",
    },
    {
        "question_type": "judge",
        "question": "进行实验时，人员头部以及上半身绝不可伸进通风柜内。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "通风柜安全要求实验时人员头部以及上半身绝不可伸进通风柜内。",
    },
    {
        "question_type": "single",
        "question": "通风柜不操作时，玻璃视窗应处于什么状态？",
        "option_a": "关闭状态",
        "option_b": "完全打开",
        "option_c": "拆下",
        "option_d": "用纸堵住",
        "answer": "A",
        "explanation": "手册要求人员不操作时，应确保通风柜玻璃视窗处于关闭状态。",
    },
    {
        "question_type": "judge",
        "question": "通风柜若发现故障，应立即关闭柜门并联系维修人员检修，切勿进行实验。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "通风柜安全要求发现故障切勿实验，应关闭柜门并联系维修。",
    },
    {
        "question_type": "single",
        "question": "使用手套箱前，为什么要摘下手表、戒指等锋利物品？",
        "option_a": "防止划破橡胶手套",
        "option_b": "防止影响拍照",
        "option_c": "防止手表走慢",
        "option_d": "没有原因",
        "answer": "A",
        "explanation": "手套箱安全要求操作前摘下手表、戒指等锋利物品，以防划破橡胶手套。",
    },
    {
        "question_type": "single",
        "question": "应急喷淋、洗眼装置的取用通道应如何保持？",
        "option_a": "畅通",
        "option_b": "堆满杂物",
        "option_c": "上锁封闭",
        "option_d": "作为储物区",
        "answer": "A",
        "explanation": "手册要求爱护应急喷淋、洗眼装置，保持取用通道畅通。",
    },
    {
        "question_type": "multi",
        "question": "实验室安全标识包括哪些分类？",
        "option_a": "禁止标识、警告标识",
        "option_b": "指令标识、提示标识",
        "option_c": "专用标识",
        "option_d": "娱乐标识",
        "answer": "ABC",
        "explanation": "附件一列明实验室安全标识分为禁止、警告、指令、提示和专用标识等。",
    },
    {
        "question_type": "single",
        "question": "禁止标识主要用于什么？",
        "option_a": "禁止人们不安全行为",
        "option_b": "提醒欣赏风景",
        "option_c": "展示课程表",
        "option_d": "标注娱乐区域",
        "answer": "A",
        "explanation": "手册附件说明禁止标识用于禁止人们不安全行为。",
    },
    {
        "question_type": "single",
        "question": "警告标识主要用于什么？",
        "option_a": "提醒人们对周围环境引起注意以避免危险",
        "option_b": "提供餐饮信息",
        "option_c": "禁止所有实验",
        "option_d": "替代安全培训",
        "answer": "A",
        "explanation": "附件一说明警告标识用于提醒人们注意周围环境，以避免可能发生危险。",
    },
    {
        "question_type": "single",
        "question": "强酸沾着皮肤时，手册建议首先如何处理？",
        "option_a": "用大量水冲洗 15 分钟",
        "option_b": "立即用纸擦干即可",
        "option_c": "直接用强碱中和",
        "option_d": "不处理继续实验",
        "answer": "A",
        "explanation": "附件四中强酸沾着皮肤时，用大量水冲洗 15 分钟，再按要求处理。",
    },
    {
        "question_type": "single",
        "question": "强碱沾着皮肤时，手册建议首先如何处理？",
        "option_a": "立刻脱去衣服，尽快用水冲洗至皮肤不滑为止",
        "option_b": "等待自然干燥",
        "option_c": "直接用手擦拭",
        "option_d": "用明火烘干",
        "answer": "A",
        "explanation": "附件四中强碱沾着皮肤时，应立刻脱去衣服，尽快用水冲洗至皮肤不滑。",
    },
    {
        "question_type": "single",
        "question": "吸入卤素气后，第一步通常应如何处理？",
        "option_a": "把患者转移到空气新鲜的地方并保持安静",
        "option_b": "继续留在污染区域",
        "option_c": "剧烈运动",
        "option_d": "立即饮酒",
        "answer": "A",
        "explanation": "附件四中卤素气处理要求把患者转移到空气新鲜的地方，保持安静。",
    },
    {
        "question_type": "single",
        "question": "误吞重金属时，可饮服什么使其吸附胃中的重金属？",
        "option_a": "牛奶、蛋白或丹宁酸等",
        "option_b": "汽油",
        "option_c": "强酸",
        "option_d": "浓碱",
        "answer": "A",
        "explanation": "附件四说明误吞重金属时，可饮服牛奶、蛋白或丹宁酸等，使其吸附胃中的重金属。",
    },
    {
        "question_type": "single",
        "question": "烃类化合物误吞后，为什么应尽量避免洗胃或用催吐剂催吐？",
        "option_a": "呕吐物进入呼吸道可能发生严重危险事故",
        "option_b": "因为烃类完全无害",
        "option_c": "因为无需任何处理",
        "option_d": "为了节省时间",
        "answer": "A",
        "explanation": "附件四指出烃类化合物误吞后应尽量避免洗胃或催吐，防止呕吐物进入呼吸道造成严重危险。",
    },
    {
        "question_type": "single",
        "question": "一氧化碳中毒处理中，应将患者转移到哪里？",
        "option_a": "空气新鲜的地方",
        "option_b": "密闭污染区域",
        "option_c": "火源附近",
        "option_d": "高温烘箱旁",
        "answer": "A",
        "explanation": "附件四说明一氧化碳中毒应清除火源，将患者转移到空气新鲜的地方并保持安静、输氧。",
    },
    {
        "question_type": "judge",
        "question": "实验室安全承诺书要求本人承诺严格遵守实验室各项安全制度和操作规程。",
        "option_a": "正确",
        "option_b": "错误",
        "option_c": "",
        "option_d": "",
        "answer": "T",
        "explanation": "手册末尾承诺书要求学习手册并承诺严格遵守实验室安全制度和操作规程。",
    },
]


def extract_pdf_text() -> tuple[int, str]:
    reader = PdfReader(str(PDF_PATH))
    pages = []
    for index, page in enumerate(reader.pages, 1):
        pages.append(f"\n\n===== Page {index} =====\n")
        pages.append(page.extract_text() or "")
    return len(reader.pages), "".join(pages).strip()


def write_csv() -> None:
    fields = [
        "question",
        "question_type",
        "option_a",
        "option_b",
        "option_c",
        "option_d",
        "answer",
        "explanation",
        "source",
    ]
    with CSV_PATH.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for item in QUESTIONS:
            row = {field: item.get(field, "") for field in fields}
            row["source"] = SOURCE
            writer.writerow(row)


def import_questions() -> tuple[int, int]:
    bank = app.QuestionBank(app.DB_PATH)
    imported = 0
    skipped = 0
    with bank._connect() as conn:  # noqa: SLF001 - utility script for this app
        for item in QUESTIONS:
            norm = app.normalize_text(item["question"])
            exists = conn.execute(
                "SELECT 1 FROM questions WHERE normalized_question = ? LIMIT 1",
                (norm,),
            ).fetchone()
            if exists:
                skipped += 1
                continue
            bank.save(
                question=item["question"],
                option_a=item.get("option_a", ""),
                option_b=item.get("option_b", ""),
                option_c=item.get("option_c", ""),
                option_d=item.get("option_d", ""),
                question_type=item["question_type"],
                answer=item["answer"],
                explanation=item.get("explanation", ""),
                source=SOURCE,
                conn=conn,
            )
            imported += 1
    return imported, skipped


def main() -> int:
    if not PDF_PATH.exists():
        print(f"PDF 不存在：{PDF_PATH}", file=sys.stderr)
        return 1

    page_count, text = extract_pdf_text()
    TEXT_PATH.write_text(text, encoding="utf-8")
    write_csv()
    imported, skipped = import_questions()

    print(f"PDF 页数：{page_count}")
    print(f"抽取文本：{TEXT_PATH}")
    print(f"生成题库 CSV：{CSV_PATH}")
    print(f"题目总数：{len(QUESTIONS)}")
    print(f"新导入：{imported}")
    print(f"已存在跳过：{skipped}")
    print(f"来源标记：{SOURCE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
